### PR TITLE
Lifetime options

### PR DESCRIPTION
**Pull request by ghost**
I haven't tested this, so I don't know if it'll work or not.
This change replaces "expiresecs" with "maxexpiresecs" and should allow a "life=" parameter which sets the lifetime in seconds.

### CODE REVIEW

**Comment by vifino** [comment]
Did you try it and confirm that it is working?

**Comment by ghost** [comment]
I haven't set it up yet, so unfortunately no.

**Comment by vifino** [comment]
I'll try it later.

**Comment by vifino** [comment]
Don't change indentation and don't mix indentation.
Reformat with Tabs, like the original source.

**Comment by ghost** [comment]
Now invalid due to conflicts and neglect

**Pull request closed without merging**
